// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcKH7OMM8xO38frgpUqVioO_iwKd6vqWI',
    appId: '1:155683237802:web:da28b9e39217a2b150c5d3',
    messagingSenderId: '155683237802',
    projectId: 'zajomotors-b3add',
    authDomain: 'zajomotors-b3add.firebaseapp.com',
    storageBucket: 'zajomotors-b3add.firebasestorage.app',
    measurementId: 'G-1QJVFEWK7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAinzS1Xfi1QynXsY82JXKzS5ZTdfrc2k0',
    appId: '1:155683237802:android:c4ccd90968f717ce50c5d3',
    messagingSenderId: '155683237802',
    projectId: 'zajomotors-b3add',
    storageBucket: 'zajomotors-b3add.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq9EVq5be69-LyH39fvIBDgpiVFLBm7xI',
    appId: '1:155683237802:ios:286abaf1c919352150c5d3',
    messagingSenderId: '155683237802',
    projectId: 'zajomotors-b3add',
    storageBucket: 'zajomotors-b3add.firebasestorage.app',
    iosBundleId: 'com.example.zajoMotors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq9EVq5be69-LyH39fvIBDgpiVFLBm7xI',
    appId: '1:155683237802:ios:286abaf1c919352150c5d3',
    messagingSenderId: '155683237802',
    projectId: 'zajomotors-b3add',
    storageBucket: 'zajomotors-b3add.firebasestorage.app',
    iosBundleId: 'com.example.zajoMotors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcKH7OMM8xO38frgpUqVioO_iwKd6vqWI',
    appId: '1:155683237802:web:719c0df272fb46a150c5d3',
    messagingSenderId: '155683237802',
    projectId: 'zajomotors-b3add',
    authDomain: 'zajomotors-b3add.firebaseapp.com',
    storageBucket: 'zajomotors-b3add.firebasestorage.app',
    measurementId: 'G-KC2KDXD6LK',
  );
}
